modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
license="MIT"
issueTrackerURL="https://github.com/seymourimadeit/ambientbirds/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="flockingbirds" #mandatory
version="1.0.1" #mandatory
displayName="Flocking Birds" #mandatory
#updateJSONURL="https://raw.githubusercontent.com/seymourimadeit/guardvillagers/master/update.json" #optional
#displayURL="https://www.curseforge.com/minecraft/mc-mods/guard-villagers" #optional
credits="TallestRed" #optional
authors="TallestRed." #optional
description='''
Birds that flock!
'''
[[dependencies.ambientbirds]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32.0.65,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.ambientbirds]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,]"
    ordering="NONE"
    side="BOTH"